package emploHibernate;
// Generated Aug 7, 2022 4:56:46 PM by Hibernate Tools 4.3.1



/**
 * Empdetails generated by hbm2java
 */
public class Empdetails  implements java.io.Serializable {


     private String empId;
     private String empName;
     private int age;
     private String nic;
     private String gender;
     private String contactNo;
     private String email;
     private String address;
     private String position;

    public Empdetails() {
    }

	
    public Empdetails(String empId, String empName, int age, String nic, String contactNo, String email, String address, String position) {
        this.empId = empId;
        this.empName = empName;
        this.age = age;
        this.nic = nic;
        this.contactNo = contactNo;
        this.email = email;
        this.address = address;
        this.position = position;
    }
    public Empdetails(String empId, String empName, int age, String nic, String gender, String contactNo, String email, String address, String position) {
       this.empId = empId;
       this.empName = empName;
       this.age = age;
       this.nic = nic;
       this.gender = gender;
       this.contactNo = contactNo;
       this.email = email;
       this.address = address;
       this.position = position;
    }
   
    public String getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(String empId) {
        this.empId = empId;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }




}


